version: "2"
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""
linters:
  enable:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - gocritic
    - gosec
    - ireturn
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nonamedreturns
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - whitespace
  disable:
    - unused
  settings:
    lll:
      line-length: 160
    revive:
      rules:
        - name: dot-imports
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - allowed-packages: ["github.com/onsi/ginkgo/v2", "github.com/onsi/gomega"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kiwicom/k8s-vault-operator)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
