version: '3'

services:
  vault:
    image: vault:1.12.2
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_LOG_LEVEL: trace

  runner:
    image: golang:alpine
    cap_add:
      - IPC_LOCK
    environment:
      GOPROXY: https://goproxy.io
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: testtoken
    volumes:
    - .:/app
